# syntax=docker/dockerfile:1.7
FROM node:24.15.0-alpine AS builder
ARG APP_VERSION
ARG APP_BUILD_ID
ENV APP_VERSION=$APP_VERSION
ENV APP_BUILD_ID=$APP_BUILD_ID
ENV VITE_APP_VERSION=$APP_VERSION
ENV VITE_APP_BUILD_ID=$APP_BUILD_ID
ARG VITE_IOS_SHORTCUT_URL
ENV VITE_IOS_SHORTCUT_URL=$VITE_IOS_SHORTCUT_URL
ARG VITE_SENTRY_DSN
ARG VITE_SENTRY_ENVIRONMENT=production
ARG VITE_SENTRY_TRACES_SAMPLE_RATE=0.05
ARG SENTRY_UPLOAD_ENABLED=false
ARG SENTRY_ORG
ARG SENTRY_PROJECT=ww-bill-client
ENV VITE_SENTRY_DSN=$VITE_SENTRY_DSN
ENV VITE_SENTRY_ENVIRONMENT=$VITE_SENTRY_ENVIRONMENT
ENV VITE_SENTRY_TRACES_SAMPLE_RATE=$VITE_SENTRY_TRACES_SAMPLE_RATE
ENV SENTRY_UPLOAD_ENABLED=$SENTRY_UPLOAD_ENABLED
ENV SENTRY_ORG=$SENTRY_ORG
ENV SENTRY_PROJECT=$SENTRY_PROJECT
WORKDIR /app
#RUN npm config set registry https://registry.npmmirror.com
RUN npm i -g pnpm@10
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN --mount=type=secret,id=sentry_auth_token,env=SENTRY_AUTH_TOKEN pnpm build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
