// Business names share the official Lucide glyph mapping across hosts.
export const designIconNames = {
  'action-asset': 'WalletCards',
  'action-exchange': 'ArrowRightLeft',
  'action-invoice': 'ReceiptText',
  'amount-hidden': 'EyeOff',
  'amount-visible': 'Eye',
  'auth-lock': 'LockKeyhole',
  'avatar-edit': 'Pencil',
  'avatar-user': 'UserRound',
  'calendar': 'CalendarDays',
  'chart-selector-chevron': 'ChevronDown',
  'check-in': 'CalendarCheck2',
  'discovery-asset': 'WalletCards',
  'discovery-bill': 'ReceiptText',
  'discovery-budget': 'ChartPie',
  'empty-alert': 'CircleAlert',
  'empty-retry': 'RefreshCw',
  'editor-back': 'ArrowLeft',
  'editor-date': 'CalendarDays',
  'editor-time': 'Clock3',
  'editor-delete': 'Delete',
  'list-chevron': 'ChevronRight',
  'mine-badge': 'Award',
  'profile-title': 'Medal',
  'mine-invite': 'Gift',
  'mine-message': 'MessageSquare',
  'mine-points': 'Star',
  'mine-settings': 'Settings',
  'period-previous': 'ChevronLeft',
  'period-next': 'ChevronRight',
  'sheet-close': 'X',
  'period-selected': 'Check',
  'period-chevron': 'ChevronRight',
  'search': 'Search',
  'shortcut-asset': 'WalletCards',
  'shortcut-bill': 'ReceiptText',
  'shortcut-budget': 'ChartPie',
  'tab-add': 'Plus',
  'tab-chart-active': 'ChartColumn',
  'tab-chart': 'ChartColumn',
  'tab-detail-active': 'ReceiptText',
  'tab-detail': 'ReceiptText',
  'tab-discovery-active': 'Compass',
  'tab-discovery': 'Compass',
  'tab-mine-active': 'UserRound',
  'tab-mine': 'UserRound',
  'vip-crown': 'Crown',
  'record-attachment': 'Image',
} as const;

export type DesignIconName = keyof typeof designIconNames;
