/** Adapted from Konsta 5.4.0 use-ios-tabbar-highlight.js; see docs/licenses/konsta-MIT.txt. */
export function getTabbarProgress(clientX: number, left: number, width: number, count: number): number {
  if (width <= 0 || count <= 0)
    return 0;
  const step = width / count;
  return Math.max(0, Math.min(count - 1, (clientX - left - step / 2) / step));
}

interface TabbarGestureOptions {
  element: HTMLElement;
  getActiveIndex: () => number;
  onPress: (pressed: boolean) => void;
  onProgress: (progress: number) => void;
  onRelease: (index: number, cancelled: boolean) => void;
}

/** Owns one pointer, cancels safely, and consumes only the click generated by that gesture. */
export function attachTabbarGesture({ element, getActiveIndex, onPress, onProgress, onRelease }: TabbarGestureOptions): () => void {
  let pointerId: number | undefined;
  let progress = 0;
  let frame = 0;
  let suppressClick = false;
  let clickTimeout: ReturnType<typeof setTimeout> | undefined;
  const links = () => Array.from(element.querySelectorAll<HTMLButtonElement>('[role="tab"]'));
  const update = (event: PointerEvent) => {
    const rect = element.getBoundingClientRect();
    progress = getTabbarProgress(event.clientX, rect.left + 5, rect.width - 10, links().length);
    cancelAnimationFrame(frame);
    frame = requestAnimationFrame(() => onProgress(progress));
  };
  const handleDown = (event: PointerEvent) => {
    if (pointerId !== undefined || event.pointerType === 'mouse' || !event.isPrimary)
      return;
    if (!(event.target instanceof Element) || !event.target.closest('[role="tab"]'))
      return;
    pointerId = event.pointerId;
    suppressClick = false;
    onPress(true);
    update(event);
  };
  const handleMove = (event: PointerEvent) => {
    if (event.pointerId === pointerId)
      update(event);
  };
  const finish = (cancelled: boolean) => {
    if (pointerId === undefined)
      return;
    pointerId = undefined;
    cancelAnimationFrame(frame);
    onPress(false);
    const buttons = links();
    const index = Math.round(progress);
    const isDisabled = buttons[index]?.disabled || buttons[index]?.getAttribute('aria-disabled') === 'true';
    onRelease(cancelled || isDisabled ? getActiveIndex() : index, cancelled || Boolean(isDisabled));
    suppressClick = !cancelled;
    clearTimeout(clickTimeout);
    clickTimeout = setTimeout(() => {
      suppressClick = false;
    }, 500);
  };
  const handleEnd = (event: PointerEvent) => {
    if (event.pointerId !== pointerId)
      return;
    if (event.type === 'pointerup')
      update(event);
    finish(event.type !== 'pointerup');
  };
  const handleBlur = () => finish(true);
  const handleClick = (event: MouseEvent) => {
    if (!suppressClick || event.detail === 0)
      return;
    suppressClick = false;
    event.preventDefault();
    event.stopImmediatePropagation();
  };
  element.addEventListener('pointerdown', handleDown);
  element.addEventListener('click', handleClick, true);
  document.addEventListener('pointermove', handleMove);
  document.addEventListener('pointerup', handleEnd);
  document.addEventListener('pointercancel', handleEnd);
  window.addEventListener('blur', handleBlur);
  return () => {
    cancelAnimationFrame(frame);
    clearTimeout(clickTimeout);
    onPress(false);
    element.removeEventListener('pointerdown', handleDown);
    element.removeEventListener('click', handleClick, true);
    document.removeEventListener('pointermove', handleMove);
    document.removeEventListener('pointerup', handleEnd);
    document.removeEventListener('pointercancel', handleEnd);
    window.removeEventListener('blur', handleBlur);
  };
}
