/**
 * Development-only candidate values. They deliberately stay outside the
 * account appearance union so they can never be sent to the API.
 */
export const MONO_DEVELOPMENT_TEMPLATE = 'mono' as const;

export const MONO_DEVELOPMENT_TOKENS: Readonly<Record<string, string>> = {
  '--ww-theme-color': 'var(--ww-ref-mono-purple)',
  '--ww-theme-color-mid': 'var(--ww-ref-mono-purple-pressed)',
  '--ww-theme-color-light': 'var(--ww-ref-mono-purple-soft)',
  '--ww-theme-color-deep': 'var(--ww-ref-mono-purple-ink)',
  '--ww-primary-foreground': 'var(--ww-ref-mono-white)',
  '--ww-pink-color': 'var(--ww-ref-mono-purple)',
  '--ww-pink-color-light': 'var(--ww-ref-mono-violet-surface)',
  '--ww-theme-text-color': 'var(--ww-ref-mono-ink)',
  '--ww-text-color-mid': 'var(--ww-ref-mono-muted)',
  '--ww-text-color-soft': 'var(--ww-ref-mono-subtle)',
  '--ww-background-color': 'var(--ww-ref-mono-canvas)',
  '--ww-surface-tint-color': 'var(--ww-ref-mono-selection)',
  '--ww-surface-accent-color': 'var(--ww-ref-mono-violet-surface)',
  '--ww-surface-secondary-color': 'var(--ww-ref-mono-surface)',
  '--ww-border-color': 'var(--ww-ref-mono-border-soft)',
  '--ww-card-color': 'var(--ww-ref-mono-white)',
  '--ww-surface-color': 'var(--ww-ref-mono-white)',
  '--ww-surface-raised-color': 'var(--ww-ref-mono-white)',
  '--ww-control-surface': 'var(--ww-ref-mono-white)',
  '--ww-page-gradient': 'var(--ww-background-color)',
  '--ww-card-shadow': 'var(--ww-ref-mono-shadow-card)',
  '--ww-card-shadow-xs': 'var(--ww-ref-mono-shadow-control)',
  '--ww-card-shadow-lg': 'var(--ww-ref-mono-shadow-panel)',
  '--ww-card-shadow-floating': 'var(--ww-ref-mono-shadow-dock)',
  '--ww-control-shadow': 'var(--ww-ref-mono-shadow-control)',
  '--ww-page-gutter': '18px',
  '--ww-section-gap': '16px',
  '--ww-card-padding': '20px',
  '--ww-control-height': '52px',
  '--ww-list-row-height': '56px',
  '--ww-radius-card': '28px',
  '--ww-radius-panel': '32px',
  '--ww-radius-control': '20px',
  '--ww-card-blur': '0px',
  '--ww-color-action-primary': '118 92 255',
  '--ww-color-fg': '18 18 23',
  '--ww-color-fg-muted': '138 138 148',
  '--ww-color-fg-subtle': '182 182 191',
  '--ww-color-finance-income': '52 199 89',
  '--ww-color-finance-expense': '48 143 243',
  '--ww-color-feedback-success': '52 199 89',
  '--ww-color-feedback-warning': '255 149 0',
  '--ww-color-feedback-danger': '255 59 48',
  '--ww-chart-1': 'var(--ww-ref-mono-purple)',
  '--ww-chart-2': 'var(--ww-ref-mono-chart-purple-soft)',
  '--ww-chart-3': 'var(--ww-ref-mono-income)',
  '--ww-chart-4': 'var(--ww-ref-mono-expense)',
  '--ww-chart-5': 'var(--ww-ref-mono-warning)',
  '--ww-chart-6': 'var(--ww-ref-mono-chart-muted)',
};
